a_core/urls.py
from django.contrib import admin
from django.urls import path, include
from a_post.views import *
from a_users.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
     path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('category/<tag>', home_view, name='category'),
    path('post/create/', post_create_view, name='post-create'),
    path('post/delete/<pk>', post_delete_view, name='post-delete'),
    path('post/edit/<pk>', post_edit_view, name='post-edit'),
    path('post/<pk>', post_page_view, name='post'),
    path('post/like/<pk>/', like_post, name='like-post'),
    path('profile/', profile_view, name='profile'),
    path('<username>/', profile_view, name='userprofile'),
    path('profile/edit/', profile_edit_view, name='profile-edit'),
    path('profile/delete/', profile_delete_view, name='profile-delete'),
    path('profile/onboarding/', profile_edit_view, name='profile-onboarding'),
    path('commentsent/<pk>/', comment_sent, name="comment-sent"),
    path('comment/delete/<pk>/', comment_delete_view, name="comment-delete"),
    path('comment/like/<pk>', like_comment, name='like-comment'),
    path('reply-sent/<pk>/', reply_sent, name='reply-sent'),
    path('reply/delete/<pk>/', reply_delete_view, name="reply-delete"),
    path('reply/like/<pk>/', like_reply, name='like-reply'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

a_post/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    image = models.URLField(max_length=500)
    body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='posts') 
    tags = models.ManyToManyField('Tag')
    created_at = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='likedposts', through="LikedPost")
    id = models.CharField(max_length=100, default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created_at']

class LikedPost(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username}: {self.post.title}'

class Tag(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)
    image = models.FileField(upload_to='icons/', null=True, blank=True)

    def __str__(self):
        return self.name
    
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name ='comments')
    parent_post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    body = models.CharField(max_length=500)
    likes = models.ManyToManyField(User, related_name='likedcomments',through='LikedComment')
    created_at = models.DateTimeField(auto_now_add=True)
    id = models.CharField(max_length=100, default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        try:
            return f'{self.author.username} :{self.body[:30]}'
        except:
            return f'no author : {self.body[:30]}'
    class Meta:
        ordering = ['-created_at']

class LikedComment(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username}: {self.comment.body[:30]}'


class Reply(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='replies')
    parent_comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='replies')
    body = models.CharField(max_length=500)
    likes = models.ManyToManyField(User, related_name='likedreplies',through='LikedReply')
    created_at = models.DateTimeField(auto_now_add=True)
    id = models.CharField(max_length=150, default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        try:
            return f'{self.author.username}: {self.body[:30]}'
        except:
            return f'no author : {self.body[:30]}'
    class Meta:
        ordering = ['created_at']

class LikedReply(models.Model):
    reply = models.ForeignKey(Reply, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username}: {self.reply.body[:30]}'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Awesome</title>
    <link rel="shortcut icon" type="image/png" href="https://img.icons8.com/small/64/000000/fire-heart.png"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js" defer></script>
    <script src="https://cdn.tailwindcss.com"></script>
     <script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.8/dist/htmx.min.js"></script>
     <script src="https://unpkg.com/hyperscript.org@0.9.14"></script>
    <style type="text/tailwindcss">
        [x-cloak] { 
            display: none !important; 
        }
        :root {
            --primary: rgb(88, 40, 244);
            --primary-hover: rgb(69, 29, 200);
            --black: #1f2937;
            --font1: 'Lobster', sans-serif;
        }
        h1 {
            @apply text-4xl font-bold mb-4
        }
        h2 {
            @apply text-2xl font-bold mb-3
        }
        h3 {
            @apply text-lg font-bold 
        }
        .font1 {
            font-family: var(--font1);
        }
        .button, button, [type='submit'], [type='button'] {
            display: inline-flex;
            flex-wrap: wrap;
            align-items: center;
            justify-content: center;
            flex-shrink: 0;
            text-align: center;
            border-radius: 0.5rem;
            cursor: pointer;
            padding: 0 1rem;
            min-height: 3.3rem;
            font-weight: 600;
            box-shadow: 0 4px 3px rgba(0, 0, 0, 0.1);
            transition-property: transform;
            transition-duration: .2s;
            color: white;
            background-color: var(--primary);
            width: fit-content;
        }
        .button:hover, button:hover, [type='submit']:hover, [type='button']:hover {
            background-color: var(--primary-hover);
        }
        .button:active, button:active, [type='submit']:active, [type='button']:active {
            transform: scale(0.95);
        }
        .secondaryAction {
            background-color: white;
            color: rgba(0, 0, 0, 0.6);
            border: 1px solid rgba(0, 0, 0, 0.3);
        }
        .secondaryAction:hover, .button.secondaryAction:hover {
            background-color: rgba(0, 0, 0, 0.05);
        }
        .navitems>li>a {
            @apply flex items-center gap-2 h-12 px-4 hover:bg-gray-700 rounded-lg;
        }
        .card {
            display: flex;
            flex-direction: column;
            overflow: hidden;
            position: relative;
            border-radius: 1rem;
            box-shadow: 0 10px 15px -3px rgba(0,0,0,0.1);
            margin-bottom: 2rem;
            background-color: white;
            padding-bottom: 1rem;
            width: 100%;
        }
        .hoverlist>* {
            @apply hover:bg-gray-100 rounded-md transition duration-150;
        }
        .hoverlist>*>a {
            @apply flex items-center p-2;
        }
        .highlight {
            @apply !bg-indigo-100;
        }
        .titleBlip {
            animation: 1s fadeIn;
        }
        @keyframes fadeIn {
            0% { opacity: 0; }
            10% { opacity: 0; }
            100% { opacity: 1; }
        }
        html, body {
            margin: 0;
            min-height: 100%;
        }
        p {
            margin-bottom: 1rem;
        }
        form p {
            display: flex;
            align-items: center;
            margin-bottom: 1rem;
        }
        label, input {
          display: inline-block;
        }
        form p label {
            width: 7rem;
            }
        label {
            margin: 6px 0 3px;
        }
        input, textarea {
            width: 100%;
        }
        input[type="file"], select {
            background-color: white;
            padding-left: 0;
        }
        label[for="id_remember"] {
            width: auto;
            margin-right: 0.5rem;
        }
        input[name="remember"] {
            width: auto;
        }
        .btn-red {
            @apply inline-flex bg-red-500;
        }
        .btn-red:hover {
            @apply bg-red-600;
        }
        .login .secondaryAction {
            box-shadow: none;
            display: block;
            padding: none;
            padding: 0px;
            border: none;
            font-size: smaller;
            font-weight: normal;
            min-height: auto;
            margin-bottom: 1.5rem;
        }
        .login .secondaryAction:hover {
            @apply text-gray-500 underline bg-white;
        }
        #id_tags {
            margin-bottom: 1rem;
        }
        #id_tags div {
            display: inline-block;
            margin-right: 0.5rem;  
        }
        #id_tags div label {
            border-radius: 9999px;
            padding: 0.5rem 1rem;
            border: 1px solid rgb(229 231 235);
            width: auto;
            cursor: pointer;
            user-select: none;
        }
        #id_tags input {
            display: none;
        }
        #id_tags label:has(input:checked) {
            background-color: var(--black);
            color: white;
            border: 1px solid var(--black);
        }
        .textarea, textarea {
            margin-bottom: 1rem;
        }
        .textarea, textarea, input {
            border-radius: 0.5rem;
            padding: 1rem 1.2rem;
            background-color: rgba(232, 240, 254, 1);
        }
        .errorlist li {
            color: rgb(253, 88, 49);
            padding: 0.5rem;
            padding-left: 1rem;
            border-left: 5px solid rgb(253, 88, 49);
            margin-bottom: 1rem;
        }
        .tab {
            cursor: pointer;
            padding: 0.75rem 1rem;
            color: rgb(0,0,0,0.6); 
            background-color: rgb(0,0,0,0.05);
            border-radius: 0.75rem;
            text-align: center;
            display: flex;
            align-items: center;
        }
        .tab:hover {
            background-color: rgb(0,0,0,0.1);
        }
        .tab.selected {
            color: white;
            background-color: var(--black);
        }
        .replyform {
            border-top: none;
        }
        .replyform textarea, .replyform input {
            padding: 0.75rem 1rem;
            font-size: 1rem;
            margin-bottom: 0px;
            height: 3.2rem;
        }
        .replyform button {
            margin-left: 0.5rem;
            min-height: unset;
        }
        .fade-me-in.htmx-settling{
            opacity: 0;
        }
        .fade-me-in {
            opacity: 1;
            transition: opacity 1s ease-out;
        }
        #profile article figure img {
            @apply aspect-[3/2] object-cover;
        }
        #profile article p {
            @apply truncate leading-normal;
        }
    </style>
</head>
<body class="bg-gray-100">
    {% include "includes/messages.html" %}
{% include "includes/header.html" %}



{% block layout %}
  
{% endblock layout %}
    
</body>
</html>